packages/frontend/web/src/app.tsx
packages/frontend/web/src/components/navbar.tsx
packages/frontend/web/src/components/post.tsx
packages/frontend/web/src/pages/create-post-page.tsx
packages/frontend/web/src/pages/feed.tsx

add some responsive, fix navbar and add go back modal on create page

---

packages/frontend/web/src/pages/feed.tsx
packages/frontend/web/src/pages/login.tsx
packages/frontend/web/src/utils/text-formating.tsx

fix getTimeAgo + padding on the feed

---

deployment/docker-compose.staging.yml
packages/frontend/web/Dockerfile

fix front Dockerfile

---

.github/workflows/production.yml
deployment/docker-compose.production.yml
deployment/fetch-and-deploy-production.sh
deployment/fetch-and-deploy-staging.sh
packages/backend/api/Dockerfile
packages/backend/migrations/Dockerfile
packages/frontend/web/Dockerfile

add production workflow

---

packages/backend/api/Dockerfile

aï caramba

---

packages/backend/api/package.production.json
packages/backend/api/rollup.config.js

put the sharp in the thing

---

packages/frontend/web/src/components/user-suggestion-item.tsx

User suggestion Css fix

---

packages/backend/api/src/utils/file-upload-manager.ts

1 - fix picture upload issue

---

packages/backend/api/src/models/post-model.ts
packages/backend/api/src/utils/not-null.ts
packages/frontend/web/src/components/post.tsx

add follow on feed page

---

packages/backend/api/src/subrouters/suggestions-router.ts
packages/frontend/web/src/components/user-suggestion.tsx

Suggestion-router userId Fix

---

packages/frontend/web/src/components/post.tsx

fix profile picture display on the feed

---

packages/backend/api/src/subrouters/register-router.ts
packages/frontend/web/src/components/register.tsx

limit usernames to a list of possible characters

---

packages/backend/api/src/models/user-model.ts

user-suggestion-logic fix

---

packages/backend/api/src/models/model-types.ts
packages/backend/api/src/models/post-model.ts
packages/backend/api/src/models/user-model.ts
packages/backend/api/src/subrouters/users-router.ts
packages/frontend/web/src/api-connection/post-api-connection.ts
packages/frontend/web/src/api-connection/user-api-connection.ts
packages/frontend/web/src/components/user-profiles-posts.tsx
packages/frontend/web/src/components/user-profiles.tsx
packages/frontend/web/src/pages/other-profile.tsx
packages/frontend/web/src/pages/posts.tsx
packages/frontend/web/src/pages/profile-page.tsx

fix details in user profiles

---

packages/frontend/web/src/api-connection/logout-api-connection.ts
packages/frontend/web/src/pages/parameters.tsx

add logout

---

packages/backend/api/src/models/model-types.ts
packages/backend/api/src/models/post-like-model.ts
packages/backend/api/src/subrouters/posts-router.ts
packages/frontend/web/src/api-connection/post-like-api-connection.ts
packages/frontend/web/src/components/post-comments.tsx
packages/frontend/web/src/components/post-likes-like-item.tsx
packages/frontend/web/src/components/post-likes.tsx
packages/frontend/web/src/components/post.tsx

add like list on post

---

packages/frontend/web/src/components/user-profiles-posts.tsx
packages/frontend/web/src/components/user-profiles.tsx
packages/frontend/web/src/pages/other-profile.tsx
packages/frontend/web/src/pages/profile-page.tsx

Profile css fix

---

packages/backend/api/src/models/post-model.ts

fix delete post

---

packages/frontend/web/src/components/post-likes.tsx

scrollbar fix

---

packages/frontend/web/src/components/comment.tsx
packages/frontend/web/src/components/post-comments.tsx

fix pp fix in comments + error message style
